### ISSUE TITLE
Exception when trying to access a non-owned module

### ISSUE THREAD

**Issue by pvillega** [play-modules/modules.playframework.org#2]
If trying to access a module you don't own via the owner url, an exception is raised. We should get a 404 error. It may be related to module keys not being trimmed

Example:
http://www.playmodules.net/modules/my/versions/scalikejdbc-play-plugin 

Stacktrace:

play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[NullPointerException: null]]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:134) [play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) [play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at akka.actor.Actor$class.apply(Actor.scala:318) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) [play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Mailbox.run(Mailbox.scala:179) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:516) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [com.typesafe.akka.akka-actor-akka-actor-2.0.2.jar:2.0.2]

Caused by: java.lang.NullPointerException: null
    at views.html.modules.manageVersionsForm$.apply(manageVersionsForm.template.scala:50) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at views.html.modules.manageVersionsForm$.render(manageVersionsForm.template.scala:141) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at views.html.modules.manageVersionsForm.render(manageVersionsForm.template.scala) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at controllers.Modules.showVersionManagement(Modules.java:154) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at Routes$$anonfun$routes$1$$anonfun$apply$29$$anonfun$apply$30.apply(routes_routing.scala:336) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:na]
    at Routes$$anonfun$routes$1$$anonfun$apply$29$$anonfun$apply$30.apply(routes_routing.scala:336) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:na]
    at play.core.Router$HandlerInvoker$$anon$5$$anon$1.invocation(Router.scala:1090) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:33) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.GlobalSettings$1.call(GlobalSettings.java:57) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at actions.CurrentUser.call(CurrentUser.java:34) ~[module-repo_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at be.objectify.deadbolt.actions.RoleHolderPresentAction.call(RoleHolderPresentAction.java:53) ~[be.objectify.deadbolt-2_2.9.1-deadbolt-2_2.9.1-1.1.2.jar:1.1.2]
    at play.core.j.JavaAction$class.apply(JavaAction.scala:74) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.Router$HandlerInvoker$$anon$5$$anon$1.apply(Router.scala:1089) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1$$anonfun$6.apply(Invoker.scala:126) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1$$anonfun$6.apply(Invoker.scala:126) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:17) ~[play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:125) [play.play_2.9.1-play_2.9.1-2.0.4.jar:2.0.4]
    ... 11 common frames omitted

**Comment by pvillega** [comment]
Closing to clean new PR notifications in Github, as project is abandoned
